spring.application.name=site-generation
spring.profiles.active=dev

file.path.themes=themes
file.path.templates=templates

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

spring.ai.openai.api-key=${CHAT_GPT_API_KEY}
spring.ai.openai.chat.model=gpt-5.5
spring.ai.openai.chat.timeout=25m

app.domain=vmi3519647.contaboserver.net
