spring.application.name=site-generation
spring.profiles.active=dev

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.ai.ollama.init.pull-model-strategy=when_missing
spring.ai.ollama.init.max-retries=3
spring.ai.ollama.init.timeout=10m
spring.ai.ollama.chat.keep-alive=30m
spring.ai.ollama.chat.model=qwen3:7b

themes.path="/themes"