# DB props
spring.datasource.url=jdbc:postgresql://postgres-elias-db-dev:5432/postgres-elias-db
spring.datasource.username=postgres-elias
spring.datasource.password=E2f3gLxi

# App props
app.base-url=http://169.58.203.21:40302
app.doc-url=${app.base-url}/swagger-ui/index.html