spring.application.name=site-generation
spring.profiles.active=prod

file.path.themes=themes
file.path.templates=templates

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

spring.ai.openai.api-key=${CHAT_GPT_API_KEY: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}
spring.ai.openai.chat.model=gpt-5.5
spring.ai.openai.chat.timeout=25m
