spring.datasource.url=jdbc:postgresql://postgres-elias-db:5432/postgres-elias-db
spring.datasource.username=postgres-elias
spring.datasource.password=K8a0dPqc

app.doc-url=http://194.163.164.118:40401/swagger-ui/index.html