spring.datasource.url=jdbc:postgresql://169.58.203.21:40401/postgres-elias-db
spring.datasource.username=postgres-elias
spring.datasource.password=K8a0dPqc

app.doc-url=http://localhost:8080/swagger-ui/index.html