version: '3.9'

services:
  site-generation:
    build: ../../site-generation
    expose:
      - "40400"
    restart: always
    depends_on:
      - postgres-elias-db

  postgres-elias-db:
    image: mongo:7
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    volumes:
      - mongo-db-elias:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval \"db.adminCommand('ping')\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  mongo-db-elias:
